My library
przytop/goit-team-project-js-group-1 pull request #15
Opened 2024-07-30 17:10 UTC by Szyszeekk

2024-07-30 21:41 UTC, przytop requested changes

2024-07-30 21:41 UTC, przytop commented on src/css/styles.css
> +
utwórz swój plik css i wrzuć ten kod
podepnij go do main.js

2024-07-30 21:41 UTC, przytop commented on src/js/main.js
> +
podepnij swój skrypt tutaj

2024-07-30 21:41 UTC, przytop commented on src/library.html
> +    <script src="./js/library.js" defer></script>
usuń

2024-07-30 21:41 UTC, przytop commented on src/library.html
> +        <div class="my-library-background">
najlepiej jak dasz ten kod oddzielnie w pliku html
i podepniesz tutaj jako load

2024-07-30 21:41 UTC, przytop commented on src/js/library.js
> +renderMovieList();
jak ma się odpalić z błędem to lepiej zakomentuj

2024-07-30 21:41 UTC, przytop commented on src/css/styles.css
> +body {
raczej niepotrzebnie nadpisujesz
część rzeczy jest już ustawiona w styles.css

i sprawdź też vary

2024-08-01 17:32 UTC, Szyszeekk commented on src/css/styles.css
> +
Pod main.js, a nie styles.css?

2024-08-01 17:33 UTC, Szyszeekk commented on src/css/styles.css
> +body {
jakie vary sprawdzić?

2024-08-01 17:34 UTC, Szyszeekk commented on src/js/main.js
> +
W jaki dokładnie sposób to zrobić?

2024-08-01 18:51 UTC, przytop commented on src/css/styles.css
> +
tak pod styles

2024-08-02 17:14 UTC, przytop commented on src/js/main.js
> +import './library.js';
końcówki nie musisz dawać on i tak widzi

2024-08-02 17:16 UTC, przytop commented on src/css/styles.css
> +@media screen and () {
tego nie ma

2024-08-02 17:17 UTC, przytop commented on src/css/styles.css
> -@media screen and (min-width: 768px) and (max-width: 1199px) {
usunąłeś dwa media
zrób git merge origin na swoim branchu

2024-08-02 17:19 UTC, przytop commented on src/css/library.css
> +    url(../img/cinema\ seats.jpg);
dziwna nazwa jpg

2024-08-02 17:20 UTC, przytop commented on src/css/library.css
> +  font-family: Roboto;
czcionki też możesz użyć jako var

2024-08-02 17:21 UTC, przytop commented on src/css/library.css
> +  font-family: Roboto;
i nadawaj tam gdzie trzeba, bo domyślnie on została nadana na cały projekt
w kilku miejscach coś może się zmienić więc trzeba nadpisać

2024-08-02 17:37 UTC, przytop commented on src/library.html
> -    <link
modern-normalize zostaje
tak samo link do styles.css

2024-08-02 17:40 UTC, przytop commented on src/partials/library-partial.html
> +<div class="my-library-background">
zacznij jako section i nadaj class container

2024-08-02 17:40 UTC, przytop requested changes
poprawki

2024-08-02 21:27 UTC, przytop commented on src/css/library.css
> +  .my-library-header {
dodaj przerwy

2024-08-02 21:27 UTC, przytop commented on src/css/styles.css
> +@media screen and () {
to jak masz to wywal

2024-08-02 21:28 UTC, przytop commented on src/library.html
> -    <link
sprawdź czy napewno to masz

2024-08-02 21:30 UTC, przytop commented on src/partials/library-partial.html
> +<section class="my-library-background">
wszystko powinno być w sekcji w kontenerze

2024-08-02 21:31 UTC, przytop requested changes
sprawdź i popraw

2024-08-05 16:16 UTC, przytop approved these changes
ok

2024-08-05 16:16 UTC, merged