hero-1
przytop/goit-team-project-js-group-1 pull request #7
Opened 2024-07-27 19:30 UTC by Spudowski

hero section

2024-07-28 17:50 UTC, przytop requested changes

2024-07-28 17:50 UTC, przytop commented on src/catalog.html
> +    <load ="partials/hero.html" />
hero ma być zaraz za headerem
wczytaj go jako pierwszy w main

2024-07-28 17:50 UTC, przytop commented on src/css/hero.css
> +
jak coś się powtarza to możesz to połączyć w jedno na zasadzie

.watch-btn,
.details-btn {  
    width: 117px;
    height: 38px;
   }
   
  a resztę dodajesz oddzielnie, jak jest dużo powtórzeń to dużo krótszy kod będzie

2024-07-28 17:50 UTC, przytop commented on src/css/hero.css
> +    .hero {
w mediach masz dużo duplikatów ale to pewnie wiesz i to chwilowo dodałeś

2024-07-28 17:50 UTC, przytop commented on src/partials/hero.html
> +            <img src="./img/star-outline.svg" alt="star-half">
tu masz pomyłkę w alt

2024-07-29 15:38 UTC, przytop requested changes

2024-07-29 19:08 UTC, przytop requested changes
Ponów commita po tym rebase ostatnim

2024-07-29 19:09 UTC, przytop commented
Chętnie bym to wrzucił dzisiaj na maina

2024-07-29 21:01 UTC, przytop requested changes

2024-07-29 21:01 UTC, przytop commented on src/partials/hero.html
> +    <script src="/src/js/hero.js"></script>
Tutaj masz błąd ścieżki
Najlepiej usuń to i podepnij pod main.js
import './hero';

2024-07-29 21:16 UTC, Spudowski commented
wiem, zastosowanie tymczasowe żeby sprawdzić czy kod będzie śmigał na hero

On Mon, 29 Jul 2024 at 23:01, Paweł Przytomski ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/partials/hero.html
> <https://github.com/przytop/goit-team-project-js-group-1/pull/7#discussion_r1695936662>
> :
>
> > @@ -14,4 +14,6 @@ <h2 class="title">Dungeons & Dragons: Honor Among Thieves</h2>
>              <button class="details-btn">More details</button>
>          </div>
>      </div>
> +
> +    <script src="/src/js/hero.js"></script>
>
> Tutaj masz błąd ścieżki
> Najlepiej usuń to i podepnij pod main.js
> import './hero';
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/przytop/goit-team-project-js-group-1/pull/7#pullrequestreview-2206063355>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFNMOMYQPMNCMP4LOSJRXOTZO2UTZAVCNFSM6AAAAABLSDT47WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBWGA3DGMZVGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-30 21:05 UTC, przytop approved these changes
wrzucam

2024-07-30 21:05 UTC, merged